### DISCUSSION TITLE
About "frictionless describe" output

### DISCUSSION THREAD

**Discussion by aborruso** [frictionlessdata/frictionlessdata.io#668] [Q&A] [answered]
Hi,
below I have an example output.

What's the meaning of `headerJoin: ' '` or   `headerRows:    - 1`?

In the [doc](https://framework.frictionlessdata.io/docs/guides/framework/layout-guide) I have:

> If there are multiple header rows which is managed by header_rows parameter, we can set a string to be a separator for a header's cell join operation

But I do not have multiple header rows. And here a I have a space set as separator for a header's cell join operation. Does the meaning of it it's that I do not have multiline header?

And I have

> this parameters indicates where to find the header row or header rows for a multiline header

When I have `headerRows:    - 1` the meaning of it it's that I do not have multiline header?

My input is

```
field1,field2
0,a
1,b
3,a
```

Thank you

```yaml
# --------
# metadata: input_.csv
# --------

compression: ''
control: {}
dialect:
  delimiter: ','
  doubleQuote: true
  lineTerminator: "\r\n"
  quoteChar: '"'
  skipInitialSpace: false
encoding: utf-8
format: csv
hashing: md5
innerpath: ''
layout:
  header: true
  headerCase: true
  headerJoin: ' '
  headerRows:
    - 1
name: input_
path: input_.csv
profile: tabular-data-resource
schema:
  fields:
    - bareNumber: true
      format: default
      name: field1
      type: integer
    - format: default
      name: field2
      type: string
  missingValues:
    - ''
scheme: file
```
