### DISCUSSION TITLE
Specify dialect of csv output in `frictionless extract`

### DISCUSSION THREAD

**Discussion by fjuniorr** [frictionlessdata/frictionlessdata.io#715] [Q&A]
When using the `--csv` argument of `frictionless extract` it's possible to control the dialect of the CSV output (eg. use `;` as delimiter)? 

My use case is for a transforming an excel file to csv, but `frictionless transform` appears to be too much.

**Comment by lwinfree** [comment]
Hi @fjuniorr! Does this example help? https://framework.frictionlessdata.io/docs/guides/describing-data/#describing-a-resource

**Reply by fjuniorr** [reply]
I don't think so @lwinfree, but thanks for the pointer!

**Reply by aborruso** [reply]
> Hi @fjuniorr! Does this example help? https://framework.frictionlessdata.io/docs/guides/describing-data/#describing-a-resource

Hi @lwinfree a note about it.

I have this csv input

```
a;b
1;3
7;9
```

and this resource description

```
dialect:
  delimiter: ;
encoding: utf-8
format: csv
hashing: md5
name: input
path: input.csv
profile: tabular-data-resource
schema:
  fields:
    - name: a
      type: integer
    - name: b
      type: integer
scheme: file
```

As you can see I have ` delimiter: ;`, but if I run

```
frictionless extract --type resource input.yml --csv
```

the output does not match its yaml definition and I have the `,` as field delimeter.

```
a,b
1,3
7,9
```

Probably it could be interesting to have the option, a flag, to force an output that matches the yaml file.

What do you think about?
