### DISCUSSION TITLE
Transform steps documentation

### DISCUSSION THREAD

**Discussion by aborruso** [frictionlessdata/frictionlessdata.io#745] [Q&A]
Hi,
first of all thank you again and again for this great project.

I use it especially via CLI, but I think that this is a more general issue.

Reading [Transforming Data](https://framework.frictionlessdata.io/docs/guides/basic-examples/#transforming-data), I have this yaml pipeline:

```yaml
tasks:
  - type: resource
    source: countries.csv
    steps:
      - code: cell-replace
        fieldName: neighbor_id
        pattern: '22'
        replace: '2'
      - code: cell-replace
        fieldName: population
        pattern: 'n/a'
        replace: '67'
      - code: row-filter
        formula: population
      - code: field-update
        name: neighbor_id
        type: integer
      - code: table-normalize
      - code: table-write
        path: countries.csv
```

Some notes about it:

- above we have `row-filter`, and the formula is simply `population`. If I understand correctly then all the records with non-null values are filtered. Where can I read the documentation on this? [Here](https://framework.frictionlessdata.io/docs/guides/transform-steps#filter-rows)  I do not have any sentences about formula syntax;
- above we have `cell-replace`, and I have 3 parameters: `fieldName`, `pattern` and `replace`.  Where can i find which parameters can be used for each step? I have neither [here](https://framework.frictionlessdata.io/docs/references/steps-reference/#cell_replace) nor [there](https://framework.frictionlessdata.io/docs/guides/transform-steps).

I am available to help update the documentation, if there is anything I can get this kind of information from.

Thank you
