### DISCUSSION TITLE
Reset descriptor properties to default value and keep it out of metadata export

### DISCUSSION THREAD

**Discussion by fjuniorr** [frictionlessdata/frictionlessdata.io#824] [Q&A]
What is the proper way to "reset" a property in a descriptor so that it don't get exported in calls to `to_descriptor()` and similars (eg. `to_json()`)?

For example, imagine that after cleaning the data for the field:

```yaml
name: memo
type: string
missingValues: 
  - 'NA'
```

The `missingValues` property no longer applies. How can I get the following programmatically

```yaml
name: memo
type: string
```

I've tried 

```python
from frictionless import Resource, settings

url = 'https://raw.githubusercontent.com/splor-mg/datapackage-reprex/main/reprex/20230711T100325/resource.yaml'

resource = Resource(url)

resource.schema.update_field(name='memo', descriptor={'missingValues': settings.DEFAULT_MISSING_VALUES.copy()})
print(resource.schema.get_field('memo').to_yaml())
```

But I still get the default value in the metadata export:

```yaml
name: memo
type: string
missingValues:
  - ''
```
