### DISCUSSION TITLE
Resource Naming When Same Dataset Exists in Multiple Formats

### DISCUSSION THREAD

**Discussion by dsmedia** [frictionlessdata/frictionlessdata.io#931] [General]
The Frictionless specification requires unique resource names while supporting multiple paths for a single resource:

```
resource:
  name: population_data          # Single name, multiple files
  path: ['part1.csv', 'part2.csv']
```

The name uniqueness constraint appears to create a challenge when the same dataset exists in multiple formats:

```
resources:
  - name: population_data        # Cannot reuse this name
    path: data.csv
  - name: population_data        # Even though these are the same dataset
    path: data.arrow            # just in different formats
```

Currently this requires artificial name variations:
```
resources:
  - name: population_data_csv    
    path: data.csv
  - name: population_data_arrow  
    path: data.arrow
```

What approaches exist within the current specification to indicate these resources are equivalent versions of the same logical dataset? Have there been any discussions about extending the specification to handle this situation, similar to how split files are handled? The goal is to maintain the connection between format variants without relying on naming conventions. 

Thank you for any insights into current approaches or past discussions about this topic.
