### ISSUE TITLE
Community schemas: allowing less fields than are defined in the schema

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/frictionlessdata.io#635]
The Data Resource spec allows to point to an externally hosted Resource Schema ([`schema: url-or-path`](https://specs.frictionlessdata.io/data-resource/#resource-schemas)). This is great, because it allows communities to for example develop and host a **agreed upon set of Table Schemas** ([example](https://gitlab.com/oscf/camtrap-package-schemas)) and data producers within that community to indicate that they are following the shared schema:

```yaml
"resources": [
    {
      "name": "deployments",
      "path": "deployments.csv"
      "profile": "tabular-data-resource",
      "schema": "https://gitlab.com/oscf/camtrap-package-schemas/-/raw/development/deployments-table-schema.json"
    },
   {
      "name": "media",
      "path": "media.csv",
      "profile": "tabular-data-resource",
      "schema": "https://gitlab.com/oscf/camtrap-package-schemas/-/raw/development/media-table-schema.json"
    }
]
```

A very common use however, is that data producers will have **less fields in their csv files than are defined in the schema** (e.g. skipping some non-required fields that are not applicable). According to the [Table Schema specs](https://specs.frictionlessdata.io/table-schema/#descriptor), that should be possible (key word is `SHOULD`) as long as the fields are in the correct order:

> A Table Schema is represented by a descriptor. The descriptor `MUST` be a JSON `object` (JSON is defined in [RFC 4627](http://www.ietf.org/rfc/rfc4627.txt)).
> 
> It `MUST` contain a property `fields`. `fields` `MUST` be an array where each entry in the array is a field descriptor (as defined below). The order of elements in `fields` array `MUST` be the order of fields in the CSV file. **The number of elements in `fields` array `SHOULD` be exactly the same as the number of fields in the CSV file**.

Is this a correct assumption?

As in:

```
id,name,population
1,Britain,67
2,France,
```

Should be valid against (an externally hosted):

```
{
  "fields": [
    { "name": "id" },
    { "name": "neighbour_id" }, <-- Extra field
    { "name": "name" },
    { "name": "population" }
  ]
}
```

Validation in e.g. `frictionless-py` seems to require the exact same number of fields, which is a serious drawback for externally hosted schemas, so I wanted to understand first what the intention of the spec is.
