### ISSUE TITLE
Support resource descriptor referencing in data packages?

### ISSUE THREAD

**Issue by roll** [frictionlessdata/frictionlessdata.io#877]
# Overview

https://frictionlessdata.slack.com/archives/C0362US1U3G/p1652096032617629

It's a user request to support resource referencing e.g.:

```yaml
name: package
resources:
  - resource1.json
  - resource2.json
```
